Sync with SOCA 2.6.1, add vpc endpoint support

diff --git a/source/MirrorRepos/buildspec.yml b/source/MirrorRepos/buildspec.yml
--- a/source/MirrorRepos/buildspec.yml
+++ b/source/MirrorRepos/buildspec.yml
@@ -8,71 +8,105 @@ version: 0.2
 env:
   shell: bash
   exported-variables:
+    - build_dir
     - repo_dir
+    - full_repo_dir
+    - required_repos
+    - optional_repos
+    - repos
   git-credential-helper: yes
 
 phases:
   install:
-    commands:
-      - export repo_dir=$(date +%Y-%m-%d-%H-%M-%S)
-      - 'echo repo_dir=${repo_dir}'
-      - mkdir -p $repo_dir
+    commands: |
+      echo "Running install phase"
 
-      - yum -y install yum-utils createrepo groff which
-      - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
-      - python get-pip.py
-      - which pip
-      - pip install awscli
-      - ls /etc/pki/rpm-gpg
-      - yum -y install epel-release
-      - ls /etc/pki/rpm-gpg
-      - rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
-      - rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
+      set -ex
 
-      - # Copy config and source it
-      - aws s3 cp s3://${S3_MIRROR_REPO_BUCKET}/${S3_MIRROR_REPO_FOLDER}/source/scripts/config.cfg config.cfg
-      - source config.cfg
+      echo $SHELL
 
-      - yum -y install wget
-      - yum -y install make createrepo rpm-build
-      - pip install mock
+      export build_dir=$(pwd)
+      export repo_dir=$(date +%Y-%m-%d-%H-%M-%S)
+      echo repo_dir=${repo_dir}
+      mkdir -p $repo_dir
+      export full_repo_dir=$build_dir/$repo_dir
 
-      - # Install fsx lustre client
-      - curl https://fsx-lustre-client-repo-public-keys.s3.amazonaws.com/fsx-rpm-public-key.asc -o /tmp/fsx-rpm-public-key.asc
-      - aws s3 cp /tmp/fsx-rpm-public-key.asc s3://${S3_MIRROR_REPO_BUCKET}/${S3_MIRROR_REPO_FOLDER}/${repo_dir}/yum/aws-fsx/fsx-rpm-public-key.asc
-      - rpm --import /tmp/fsx-rpm-public-key.asc
-      - curl https://fsx-lustre-client-repo.s3.amazonaws.com/el/7/fsx-lustre-client.repo -o /etc/yum.repos.d/aws-fsx.repo
-      - #yum install -y kmod-lustre-client lustre-client
-      - yum --disablerepo="*" --enablerepo="aws-fsx" list available
-      - yum --disablerepo="*" --enablerepo="aws-fsx-src" list available
-      - #yumdownloader --source kmod-lustre-client
+      export centos7_repo_dir=$repo_dir/yum/centos7
+      mkdir -p $centos7_repo_dir
+      
+      yum -y install createrepo epel-release groff make rpm-build wget which yum-utils
 
-      - source config.cfg
-      - # Copy PBSPRO tarball
-      - wget -q $OPENPBS_URL
-      - aws s3 cp $OPENPBS_TGZ s3://${S3_MIRROR_REPO_BUCKET}/${S3_MIRROR_REPO_FOLDER}/${repo_dir}/source/pbspro/$PBSPRO_TGZ
-      - # Copy Python tarball
-      - wget -q $PYTHON_URL
-      - aws s3 cp $PYTHON_TGZ s3://${S3_MIRROR_REPO_BUCKET}/${S3_MIRROR_REPO_FOLDER}/${repo_dir}/source/python/$PYTHON_TGZ
-      - # Copy OpenMPI tarball
-      - wget -q $OPENMPI_URL
-      - aws s3 cp $OPENMPI_TGZ s3://${S3_MIRROR_REPO_BUCKET}/${S3_MIRROR_REPO_FOLDER}/${repo_dir}/source/openmpi/$OPENMPI_TGZ
-      - # Copy Metric Beat tarball
-      - wget -q $METRICBEAT_URL
-      - aws s3 cp $METRICBEAST_RPM s3://${S3_MIRROR_REPO_BUCKET}/${S3_MIRROR_REPO_FOLDER}/${repo_dir}/source/metricbeat/$METRICBEAST_RPM
+      yum -y install python2-pip
+      which pip
+      
+      pip install mock
 
-      - aws s3 cp --recursive s3://${S3_MIRROR_REPO_BUCKET}/${S3_MIRROR_REPO_FOLDER}/source/MirrorRepos/yum-s3-iam s3://${S3_MIRROR_REPO_BUCKET}/${S3_MIRROR_REPO_FOLDER}/${repo_dir}/source/yum-s3-iam
-      - aws s3 cp --recursive s3://${S3_MIRROR_REPO_BUCKET}/${S3_MIRROR_REPO_FOLDER}/source/MirrorRepos/yum-s3-iam yum-s3-iam
-      - cd yum-s3-iam
-      - make test
-      - aws s3 cp /root/rpmbuild/RPMS/noarch/yum-plugin-s3-iam-1.2.2-1.noarch.rpm s3://${S3_MIRROR_REPO_BUCKET}/${S3_MIRROR_REPO_FOLDER}/${repo_dir}/yum/yum-plugin-s3-iam-1.2.2-1.noarch.rpm
-      - cd ..
+      # Installation failing using pip so get package directly from AWS
+      # Save the zip file for used by private VPCs
+      wget https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
+      unzip -q awscli-exe-linux-x86_64.zip
+      ./aws/install
+      export PATH=/usr/local/bin:${PATH}
+      aws s3 cp --quiet awscli-exe-linux-x86_64.zip s3://${S3_MIRROR_REPO_BUCKET}/${S3_MIRROR_REPO_FOLDER}/${repo_dir}/source/awscli-exe-linux-x86_64.zip
+
+      ls /etc/pki/rpm-gpg
+      rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
+      rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
+
+      aws s3 cp --quiet /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7 s3://${S3_MIRROR_REPO_BUCKET}/${S3_MIRROR_REPO_FOLDER}/$centos7_repo_dir/RPM-GPG-KEY-CentOS-7
+      aws s3 cp --quiet /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7   s3://${S3_MIRROR_REPO_BUCKET}/${S3_MIRROR_REPO_FOLDER}/$centos7_repo_dir/RPM-GPG-KEY-EPEL-7
+
+      # Install fsx lustre client
+      curl https://fsx-lustre-client-repo-public-keys.s3.amazonaws.com/fsx-rpm-public-key.asc -o /tmp/fsx-rpm-public-key.asc
+      aws s3 cp --quiet /tmp/fsx-rpm-public-key.asc s3://${S3_MIRROR_REPO_BUCKET}/${S3_MIRROR_REPO_FOLDER}/${repo_dir}/yum/aws-fsx/fsx-rpm-public-key.asc
+      rpm --import /tmp/fsx-rpm-public-key.asc
+      curl https://fsx-lustre-client-repo.s3.amazonaws.com/el/7/fsx-lustre-client.repo -o /etc/yum.repos.d/aws-fsx.repo
+      #yum install -y kmod-lustre-client lustre-client
+      yum --disablerepo="*" --enablerepo="aws-fsx" list available
+      yum --disablerepo="*" --enablerepo="aws-fsx-src" list available
+      #yumdownloader --source kmod-lustre-client
+
+      # Copy config and source it
+      aws s3 cp --quiet s3://${S3_MIRROR_REPO_BUCKET}/${S3_MIRROR_REPO_FOLDER}/source/scripts/config.cfg config.cfg
+      source config.cfg
+
+      echo $BASE_OS
+
+      yum install -y $(echo ${SYSTEM_PKGS[*]} ${SCHEDULER_PKGS[*]})
+
+      yum install -y $(echo ${OPENLDAP_SERVER_PKGS[*]} ${SSSD_PKGS[*]})
+
+      # Copy PBSPRO tarball
+      wget -q $OPENPBS_URL
+      aws s3 cp --quiet $OPENPBS_TGZ s3://${S3_MIRROR_REPO_BUCKET}/${S3_MIRROR_REPO_FOLDER}/${repo_dir}/source/openpbs/$OPENPBS_TGZ
+      # Copy Python tarball
+      wget -q $PYTHON_URL
+      if [[ $(md5sum $PYTHON_TGZ | awk '{print $1}') != $PYTHON_HASH ]];  then
+          echo -e "FATAL ERROR: Checksum for Python failed. File may be compromised." > /etc/motd
+          exit 1
+      fi
+      aws s3 cp --quiet $PYTHON_TGZ s3://${S3_MIRROR_REPO_BUCKET}/${S3_MIRROR_REPO_FOLDER}/${repo_dir}/source/python/$PYTHON_TGZ
+      # Copy OpenMPI tarball
+      wget -q $OPENMPI_URL
+      aws s3 cp --quiet $OPENMPI_TGZ s3://${S3_MIRROR_REPO_BUCKET}/${S3_MIRROR_REPO_FOLDER}/${repo_dir}/source/openmpi/$OPENMPI_TGZ
+      # Copy Metric Beat tarball
+      wget -q $METRICBEAT_URL
+      aws s3 cp --quiet $METRICBEAST_RPM s3://${S3_MIRROR_REPO_BUCKET}/${S3_MIRROR_REPO_FOLDER}/${repo_dir}/source/metricbeat/$METRICBEAST_RPM
+
+      aws s3 cp --quiet --recursive s3://${S3_MIRROR_REPO_BUCKET}/${S3_MIRROR_REPO_FOLDER}/source/MirrorRepos/yum-s3-iam s3://${S3_MIRROR_REPO_BUCKET}/${S3_MIRROR_REPO_FOLDER}/${repo_dir}/source/yum-s3-iam
+      aws s3 cp --quiet --recursive s3://${S3_MIRROR_REPO_BUCKET}/${S3_MIRROR_REPO_FOLDER}/source/MirrorRepos/yum-s3-iam yum-s3-iam
+      cd yum-s3-iam
+      make rpm || true
+      make test || true
+      aws s3 cp --quiet /root/rpmbuild/RPMS/noarch/yum-plugin-s3-iam-1.2.2-1.noarch.rpm s3://${S3_MIRROR_REPO_BUCKET}/${S3_MIRROR_REPO_FOLDER}/${repo_dir}/yum/yum-plugin-s3-iam-1.2.2-1.noarch.rpm
+      cd ..
 
     finally:
       - echo "Install phase complete"
       - ls /etc/pki/rpm-gpg
 
       # Sync the intermediate results
+      - cd $build_dir
       - aws s3 sync --quiet $repo_dir s3://${S3_MIRROR_REPO_BUCKET}/${S3_MIRROR_REPO_FOLDER}/$repo_dir
     
   pre_build:
@@ -81,7 +115,7 @@ phases:
       - 'echo "mounts:"'
       - df -h
       - 'echo "Available space in current dir:"'
-      - df -h .
+      - 'date; echo "df -h ."; df -h .'
       - 'echo "List of yum repos:"'
       - yum repolist
       - 'echo "Test aws CLI"'
@@ -89,42 +123,91 @@ phases:
 
     finally:
       - echo "pre_build phase complete"
-      - 'echo repo_dir=${repo_dir}'
+      - |
+        echo "repo_dir=${repo_dir}"
+        echo "test"
 
   build:
     commands: |
       echo "Running build phase"
 
-      mkdir -p $repo_dir/yum/centos7
-      repos=( \
+      set -ex
+
+      source config.cfg
+
+      # Build Python and install required packages
+      # This is so that a PyPi mirror isn't required.
+      mkdir -p /apps/soca/$SOCA_CONFIGURATION/python/installer
+      cd /apps/soca/$SOCA_CONFIGURATION/python/installer
+      tar xzf $build_dir/$PYTHON_TGZ
+      cd Python-$PYTHON_VERSION
+      ./configure LDFLAGS="-L/usr/lib64/openssl" CPPFLAGS="-I/usr/include/openssl" -enable-loadable-sqlite-extensions --prefix=/apps/soca/$SOCA_CONFIGURATION/python/$PYTHON_VERSION
+      make
+      make install
+      cd /apps/soca/$SOCA_CONFIGURATION/python
+      compiled_python_tgz=Python-$PYTHON_VERSION-compiled.tgz
+
+      # Install Python required libraries
+      # Source environment to reload path for Python3
+      aws s3 cp --quiet s3://${S3_MIRROR_REPO_BUCKET}/${S3_MIRROR_REPO_FOLDER}/source/scripts/requirements.txt /root/
+      /apps/soca/$SOCA_CONFIGURATION/python/$PYTHON_VERSION/bin/pip3 install -r /root/requirements.txt
+
+      compiled_python_tgz=Python-${PYTHON_VERSION}-compiled.tgz
+      tar -czf $compiled_python_tgz $PYTHON_VERSION
+      aws s3 cp --quiet $compiled_python_tgz s3://${S3_MIRROR_REPO_BUCKET}/${S3_MIRROR_REPO_FOLDER}/${repo_dir}/source/python/$compiled_python_tgz
+      cd $build_dir
+
+      export required_repos=( \
           base updates extras centosplus \
-          cr \
-          #base-debuginfo \
-          fasttrack \
-          base-source updates-source extras-source centosplus-source \
-          centos-kernel centos-kernel-experimental \
           epel epel-debuginfo epel-source \
-          epel-testing epel-testing-debuginfo epel-testing-source \
           aws-fsx \
           aws-fsx-src \
       )
+      echo ${required_repos[@]}
+      
+      export optional_repos=( \
+          base-debuginfo \
+          cr \
+          fasttrack \
+          base-source updates-source extras-source centosplus-source \
+          centos-kernel centos-kernel-experimental \
+          epel-testing epel-testing-debuginfo epel-testing-source \
+      )
+      echo ${optional_repos[@]}
+      
+      export repos=( \
+          ${required_repos[@]} \
+          #${optional_repos[@]} \
+      )
+      echo ${repos[@]}
+      
       for repo in ${repos[@]}; do
-          echo -e "\nreposync --quiet -g -l -p $repo_dir/yum/centos7 --source --downloadcomps --download-metadata -r $repo"
-          if ! reposync --quiet -g -l -p $repo_dir/yum/centos7 --source --downloadcomps --download-metadata -r $repo; then
-              rc=$?
-              echo -e "warning: reposync failed with rc=$rc but trying to continue. GPC may have failed on a package."
-          fi
-          if [ -e $repo_dir/yum/centos7/$repo/comps.xml ]; then
+        date
+        echo -e "\nreposync --quiet -g -l -p $centos7_repo_dir --source --downloadcomps --download-metadata -r $repo"
+        if ! reposync --quiet -g -l -p $centos7_repo_dir --source --downloadcomps --download-metadata -r $repo; then
+            rc=$?
+            echo -e "warning: reposync failed with rc=$rc but trying to continue. GPC may have failed on a package."''
+        fi
+        date; echo "df -h ."; df -h .
+        if [ -e $centos7_repo_dir/$repo/comps.xml ]; then
             groups_arg="-g comps.xml"
-          else
+        else
             groups_arg=""
-          fi
-          echo -e "\ncreaterepo $repo_dir/yum/centos7/$repo $groups_arg"
-          createrepo $repo_dir/yum/centos7/$repo $groups_arg
+        fi
+        
+        echo -e "\ncreaterepo $centos7_repo_dir/$repo $groups_arg"
+        createrepo $centos7_repo_dir/$repo $groups_arg
+        date; echo "df -h ."; df -h .
+        echo "aws s3 sync --quiet $centos7_repo_dir/$repo s3://${S3_MIRROR_REPO_BUCKET}/${S3_MIRROR_REPO_FOLDER}/$centos7_repo_dir/$repo"
+        aws s3 sync --quiet $centos7_repo_dir/$repo s3://${S3_MIRROR_REPO_BUCKET}/${S3_MIRROR_REPO_FOLDER}/$centos7_repo_dir/$repo
+        #echo "rm -rf $centos7_repo_dir/$repo"
+        #rm -rf $centos7_repo_dir/$repo
+        #date; echo "df -h ."; df -h .
       done
 
     finally:
       - echo "build phase complete"
+      - set -x
       - aws s3 sync --quiet $repo_dir s3://${S3_MIRROR_REPO_BUCKET}/${S3_MIRROR_REPO_FOLDER}/$repo_dir
       - 'echo repo_dir=${repo_dir}'
 
diff --git a/source/templates/Scheduler.template b/source/templates/Scheduler.template
--- a/source/templates/Scheduler.template
+++ b/source/templates/Scheduler.template
@@ -1,7 +1,10 @@
 AWSTemplateFormatVersion: 2010-09-09
 Description: (SOCA) - Deploy master host.
 Parameters:
-  SocaDomain:
+  PublicVpc:
+    Type: String
+
+  SocaLocalDomain:
     Type: String
 
   HostedZoneId:
@@ -26,8 +29,8 @@ Parameters:
   NoProxy:
     Type: String
 
-  ProxyCACert:
-    Type: AWS::SSM::Parameter::Value<String>
+  ProxyCACertParameterName:
+    Type: String
 
   RepositoryBucket:
     Type: String
@@ -56,7 +59,7 @@ Parameters:
   EFSDataDns:
     Type: String
 
-  ImageId:
+  AL2ImageId:
     Type: AWS::EC2::Image::Id
 
   ComputeNodeCustomAMI:
@@ -75,22 +78,14 @@ Parameters:
     Type: String
     NoEcho: true
 
-  SchedulerPublicIP:
-    Type: String
-
-  SchedulerPublicIPAllocation:
+  ErrorSnsTopicArn:
     Type: String
 
 Resources:
   SchedulerEC2Host:
     Type: AWS::EC2::Instance
-    # The scheduler configuration scripts have a dependency on Configuration which comes last
-    CreationPolicy:
-      ResourceSignal:
-        Count: '1'
-        Timeout: PT30M
     Properties:
-      ImageId: !Ref ImageId
+      ImageId: !Ref AL2ImageId
       DisableApiTermination: false
       InstanceType: !Ref SchedulerInstanceType
       IamInstanceProfile:
@@ -99,7 +94,7 @@ Resources:
         - DeviceName: "/dev/xvda"
           Ebs:
             VolumeSize: 150
-            VolumeType: gp2
+            VolumeType: gp3
             Encrypted: true
 
       KeyName: !Ref SSHKeyPair
@@ -122,23 +117,33 @@ Resources:
           "Fn::Base64": !Sub |
             #!/bin/bash -xe
 
-            # Signal Cloudformation if the instance creates successfully or not
-            yum -y install -y aws-cfn-bootstrap
+            # Notify user of errors
             function on_exit {
-                /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource SchedulerEC2Host --region ${AWS::Region} || true
+                rc=$?
+                set +e
+                if [[ $rc -ne 0 ]]; then
+                    aws --region ${AWS::Region} sns publish --topic-arn ${ErrorSnsTopicArn} --subject "${ClusterId} Scheduler UserData failed" --message "See /var/log/cloud-init.log or grep cloud-init /var/log/messages | less for more info."
+                fi
             }
             trap on_exit EXIT
 
+            touch /root/patch-hold
+            
+            # Update to latest ssm agent
+            if yum install -y https://s3.${AWS::Region}.amazonaws.com/amazon-ssm-${AWS::Region}/latest/linux_amd64/amazon-ssm-agent.rpm; then
+                systemctl restart amazon-ssm-agent
+            fi
+
             echo export "AWS_DEFAULT_REGION=${AWS::Region}" >> /etc/environment
             echo export "NO_PROXY=${NoProxy}" >> /etc/environment
-            echo export "SOCA_BASE_OS=${ComputeNodeBaseOS}" >> /etc/environment
             echo export "SOCA_CLOUDFORMATION_STACK=${AWS::StackName}" >> /etc/environment
+            echo export "SOCA_COMPUTE_NODE_BASE_OS=${ComputeNodeBaseOS}" >> /etc/environment
             echo export "SOCA_CONFIGURATION=${ClusterId}" >> /etc/environment
-            echo export "SOCA_DOMAIN=${SocaDomain}" >> /etc/environment
             echo export "SOCA_HOSTED_ZONE_ID=${HostedZoneId}" >> /etc/environment
             echo export "SOCA_INSTALL_AMI=${ComputeNodeCustomAMI}" >> /etc/environment
             echo export "SOCA_INSTALL_BUCKET=${S3InstallBucket}" >> /etc/environment
             echo export "SOCA_INSTALL_BUCKET_FOLDER=${S3InstallFolder}" >> /etc/environment
+            echo export "SOCA_LOCAL_DOMAIN=${SocaLocalDomain}" >> /etc/environment
             echo export "SOCA_REPOSITORY_BUCKET=${RepositoryBucket}" >> /etc/environment
             echo export "SOCA_REPOSITORY_FOLDER=${RepositoryFolder}" >> /etc/environment
             echo export "SOCA_VERSION=${Version}" >> /etc/environment
@@ -147,13 +152,16 @@ Resources:
 
             # Configure using ansible
             # This can be done before configuring the proxy because S3 is accessed using the S3 VPC endpoint
-            amazon-linux-extras install -y ansible2
+            amazon-linux-extras enable ansible2
+            yum -y install ansible
             rm -rf /root/playbooks
             aws s3 cp --recursive s3://${S3InstallBucket}/${S3InstallFolder}/playbooks/ /root/playbooks/
             cd /root/playbooks
-            ansible-playbook scheduler.yml -e Region=${!AWS_DEFAULT_REGION} -e Domain=${!SOCA_DOMAIN} -e S3InstallBucket=${!SOCA_INSTALL_BUCKET} -e S3InstallFolder=${!SOCA_INSTALL_BUCKET_FOLDER} -e RepositoryBucket=${!SOCA_REPOSITORY_BUCKET} -e RepositoryFolder=${!SOCA_REPOSITORY_FOLDER} -e ClusterId=${ClusterId} -e NoProxy=${NoProxy} -e NodeType=scheduler >> /root/ansible.log 2>&1
+            ansible-playbook /root/playbooks/scheduler.yml -e Region=${!AWS_DEFAULT_REGION} -e RepositoryBucket=${!SOCA_REPOSITORY_BUCKET} -e RepositoryFolder=${!SOCA_REPOSITORY_FOLDER} -e Domain=${!SOCA_LOCAL_DOMAIN} -e S3InstallBucket=${!SOCA_INSTALL_BUCKET} -e S3InstallFolder=${!SOCA_INSTALL_BUCKET_FOLDER} -e RepositoryBucket=${!SOCA_REPOSITORY_BUCKET} -e RepositoryFolder=${!SOCA_REPOSITORY_FOLDER} -e ClusterId=${ClusterId} -e PublicVpc=${PublicVpc} -e ProxyCACertParameterName=${ProxyCACertParameterName} -e NoProxy=${NoProxy} -e EFS_APPS=${EFSAppsDns} -e EFS_DATA=${EFSDataDns} -e NodeType=scheduler >> /root/ansible.log 2>&1
 
-            source /etc/profile.d/proxy.sh
+            if [ -e /etc/profile.d/proxy.sh ]; then
+                source /etc/profile.d/proxy.sh
+            fi
 
             export PATH=$PATH:/usr/local/bin
 
@@ -174,6 +182,7 @@ Resources:
             rm -f /etc/update-motd.d/*
 
             AWS=$(which aws)
+            
             # Tag EBS disks manually as CFN ASG does not support it
             AWS_AVAIL_ZONE=$(curl http://169.254.169.254/latest/meta-data/placement/availability-zone)
             AWS_REGION="`echo \"$AWS_AVAIL_ZONE\" | sed "s/[a-z]$//"`"
@@ -185,9 +194,8 @@ Resources:
             ENI_IDS=$(aws ec2 describe-network-interfaces --filters Name=attachment.instance-id,Values="$AWS_INSTANCE_ID" --region $AWS_REGION --query "NetworkInterfaces[*].[NetworkInterfaceId]" --out text | tr "\n" " ")
             $AWS ec2 create-tags --resources $ENI_IDS --region $AWS_REGION --tags Key=Name,Value="${ClusterId} Scheduler Network Adapter" "Key=soca:ClusterId,Value=${ClusterId}"
 
-            AWS=$(which aws)
             # Save parameters in a script so they aren't exposed in /var/log/messages
-            echo "/root/SchedulerPostReboot.sh ${S3InstallBucket} ${S3InstallFolder} ${UserName} '${UserPassword}'" > /root/call-SchedulerPostReboot.sh
+            echo "/root/SchedulerPostReboot.sh ${S3InstallBucket} ${S3InstallFolder} ${UserName} '${UserPassword}' ${ErrorSnsTopicArn}" > /root/call-SchedulerPostReboot.sh
             chmod 0700 /root/call-SchedulerPostReboot.sh
             echo "@reboot $AWS s3 cp s3://${S3InstallBucket}/${S3InstallFolder}/scripts/SchedulerPostReboot.sh /root && chmod +x /root/SchedulerPostReboot.sh && /root/call-SchedulerPostReboot.sh >> /root/PostRebootConfig.log 2>&1" | crontab -
             $AWS s3 cp s3://${S3InstallBucket}/${S3InstallFolder}/scripts/config.cfg /root/
@@ -196,24 +204,17 @@ Resources:
             $AWS s3 cp s3://${S3InstallBucket}/${S3InstallFolder}/scripts/SchedulerPostReboot.sh /root/
             chmod +x /root/Scheduler.sh
             chmod +x /root/SchedulerPostReboot.sh
-            /root/Scheduler.sh ${EFSDataDns} ${EFSAppsDns} >> /root/Scheduler.sh.log 2>&1
-
-  EIPAssociationToScheduler:
-    DependsOn: SchedulerEC2Host
-    Type: AWS::EC2::EIPAssociation
-    Properties:
-      EIP: !Ref SchedulerPublicIP
-      InstanceId: !Ref SchedulerEC2Host
+            /root/Scheduler.sh ${EFSDataDns} ${EFSAppsDns} ${ErrorSnsTopicArn} >> /root/Scheduler.sh.log 2>&1
 
   SchedulerDnsRecord:
     Type: AWS::CloudFormation::CustomResource
     Properties:
       ServiceToken: !Ref UpdateDnsLambdaArn
       Hostname: "scheduler"
-      Domain: !Ref SocaDomain
+      Domain: !Ref SocaLocalDomain
       HostedZoneId: !Ref HostedZoneId
       Type: 'A'
-      PrivateIP: !GetAtt SchedulerEC2Host.PrivateIp
+      Value: !GetAtt SchedulerEC2Host.PrivateIp
 
 Outputs:
   SchedulerInstanceId:
